version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: raven
      MYSQL_USER: raven
      MYSQL_PASSWORD: raven
      MYSQL_ROOT_PASSWORD: root
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: 
      - "3308:3306"
    volumes: 
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer
    ports: 
      - "8081:8080"
    depends_on: 
      - db

  api:
    build: .
    env_file: .env
    ports: 
      - "8000:8000"
    depends_on: 
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  dbdata:
